version: '3.3'
      
volumes:
  db_data: {}
  wp_data: {}

networks:
  backend:
    driver: bridge

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - wp_data:/var/www/html
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

